In [38]:
x=5
x

5

In [39]:
x+2

7

In [40]:
x-2

3

In [41]:
x*2

10

In [42]:
x**2

25

In [43]:
x%2

1

In [44]:
x/float(2)

2.5

In [45]:
x/2

2.5

In [46]:
str(5)

'5'

In [47]:
str(3.5)

'3.5'

In [48]:
str(True)

'True'

In [49]:
int(5)

5

In [50]:
int(True)

1

In [51]:
float(5)

5.0

In [52]:
float(True)

1.0

In [53]:
bool(5)

True

In [54]:
bool(3.45)

True

In [55]:
bool(True)

True

In [56]:
my_string='awesomestring'
my_string

'awesomestring'

In [57]:
my_string*2

'awesomestringawesomestring'

In [58]:
my_string+'hello'

'awesomestringhello'

In [59]:
'some' in my_string

True

In [60]:
a='is'
b='nice'
my_list=['my','list',a,b]
my_list2=[[4,5,6,7], [3,4,5,6]]

In [61]:
my_list[1]

'list'

In [62]:
my_list[-3]

'list'

In [63]:
my_list[1:3]

['list', 'is']

In [64]:
my_list[1:]

['list', 'is', 'nice']

In [65]:
my_list[:3]

['my', 'list', 'is']

In [66]:
my_list[:]

['my', 'list', 'is', 'nice']

In [67]:
my_list2[1][0]

3

In [68]:
my_list2[1][:2]

[3, 4]

In [69]:
my_list[1][:2]

'li'

In [70]:
my_list2[:][:]

[[4, 5, 6, 7], [3, 4, 5, 6]]

In [71]:
my_list+my_list

['my', 'list', 'is', 'nice', 'my', 'list', 'is', 'nice']

In [72]:
my_list*2

['my', 'list', 'is', 'nice', 'my', 'list', 'is', 'nice']

In [73]:
my_list.index(a)

2

In [74]:
my_list.count(a)

1

In [75]:
my_list.append('!')

In [76]:
my_list

['my', 'list', 'is', 'nice', '!']

In [77]:
my_list.remove('!')

In [78]:
my_list

['my', 'list', 'is', 'nice']

In [79]:
del(my_list[0:1])

In [80]:
my_list

['list', 'is', 'nice']

In [81]:
my_list.reverse()

In [82]:
my_list

['nice', 'is', 'list']

In [83]:
my_list.extend('!')

In [84]:
my_list

['nice', 'is', 'list', '!']

In [85]:
my_list.pop(-1)

'!'

In [86]:
my_list

['nice', 'is', 'list']

In [87]:
my_list.insert(0,'!')

In [88]:
my_list

['!', 'nice', 'is', 'list']

In [89]:
my_list.sort()

In [90]:
my_list

['!', 'is', 'list', 'nice']

In [91]:
my_string[3]

's'

In [92]:
my_string[4:9]

'omest'

In [93]:
my_string.upper()

'AWESOMESTRING'

In [94]:
my_string.lower()

'awesomestring'

In [95]:
my_string.count('w')

1

In [96]:
my_string.replace('e', 'i')

'awisomistring'

In [97]:
my_string.strip()

'awesomestring'

In [98]:
import numpy

In [99]:
import numpy as np

In [100]:
from math import pi

In [101]:
my_list = [1, 2, 3, 4]

In [102]:
my_array = np.array(my_list)

In [103]:
my_array[2]

3

In [105]:
my_2darray = np.array([[1, 2, 3], [4, 5, 6]])

In [106]:
my_array[0:2]

array([1, 2])

In [107]:
my_2darray[:,0]

array([1, 4])

In [108]:
my_array > 3

array([False, False, False,  True])

In [109]:
my_array * 2

array([2, 4, 6, 8])

In [110]:
my_array + np.array([5, 6, 7, 8])

array([ 6,  8, 10, 12])

In [111]:
my_array.shape

(4,)

In [113]:
np.insert(my_array, 1, 5)

array([1, 5, 2, 3, 4])

In [114]:
np.delete(my_array, [1])

array([1, 3, 4])

In [115]:
np.mean(my_array)

2.5

In [116]:
np.median(my_array)

2.5

In [118]:
np.std(my_array)

1.118033988749895

In [120]:
import numpy as np
import pandas as pd

In [122]:
filename = 'huck_finn.txt'
file = open(filename, mode='r')
text = file.read()
print(file.closed)
file.close()
print(text)

False
Hello Anaconda


In [124]:
with open('huck_finn.txt', 'r') as file:
    print(file.readline())
    print(file.readline())
    print(file.readline())

Hello Anaconda

Second line

#3 line



In [131]:
filename = 'mnist.txt'
data = np.loadtxt(filename,
                  delimiter=',',
                  skiprows=2,
                  usecols=[0,2],
                  dtype=str)

IndexError: list index out of range

In [ ]:
from sqlalchemy import create_engine