In [17]:
import numpy as np

In [18]:
a = np.array([1, 2, 3])
b = np.array([(1.5, 2, 3), (4, 6, 5)], dtype = float)
c = np.array([[(1.5, 2, 3), (4, 6, 5)], [(3, 2, 1), (4, 5, 6)]], dtype = float)

In [19]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
np.ones((2, 3, 4), dtype = np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [27]:
d = np.arange(10, 25, 5)
d

array([10, 15, 20])

In [22]:
np.linspace(0, 2, 9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [28]:
e = np.full((2, 2), 7)
e

array([[7, 7],
       [7, 7]])

In [29]:
f = np.eye(2)
f

array([[1., 0.],
       [0., 1.]])

In [25]:
np.random.random((2,2))

array([[0.5134415 , 0.41752867],
       [0.09449841, 0.74483613]])

In [26]:
np.empty((3,2))

array([[1.39069238e-309, 1.39069238e-309],
       [1.39069238e-309, 1.39069238e-309],
       [1.39069238e-309, 1.39069238e-309]])

In [30]:
np.save('my_array', a)

In [31]:
np.load('my_array.npy')

array([1, 2, 3])

In [32]:
a.shape

(3,)

In [33]:
len(a)

3

In [34]:
b.ndim

2

In [35]:
e.size

4

In [36]:
b.dtype

dtype('float64')

In [37]:
b.dtype.name

'float64'

In [38]:
b.astype(int)

array([[1, 2, 3],
       [4, 6, 5]])

In [40]:
g = a - b
g

array([[-0.5,  0. ,  0. ],
       [-3. , -4. , -2. ]])

In [42]:
np.subtract(a,b)

array([[-0.5,  0. ,  0. ],
       [-3. , -4. , -2. ]])

In [43]:
b + a

array([[2.5, 4. , 6. ],
       [5. , 8. , 8. ]])

In [44]:
np.add(a,b)

array([[2.5, 4. , 6. ],
       [5. , 8. , 8. ]])

In [45]:
a / b

array([[0.66666667, 1.        , 1.        ],
       [0.25      , 0.33333333, 0.6       ]])

In [46]:
np.divide(a,b)

array([[0.66666667, 1.        , 1.        ],
       [0.25      , 0.33333333, 0.6       ]])

In [47]:
a * b

array([[ 1.5,  4. ,  9. ],
       [ 4. , 12. , 15. ]])

In [48]:
np.multiply(a,b)

array([[ 1.5,  4. ,  9. ],
       [ 4. , 12. , 15. ]])

In [49]:
np.exp(b)

array([[  4.48168907,   7.3890561 ,  20.08553692],
       [ 54.59815003, 403.42879349, 148.4131591 ]])

In [50]:
np.sqrt(b)

array([[1.22474487, 1.41421356, 1.73205081],
       [2.        , 2.44948974, 2.23606798]])

In [51]:
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

In [52]:
np.cos(b)

array([[ 0.0707372 , -0.41614684, -0.9899925 ],
       [-0.65364362,  0.96017029,  0.28366219]])

In [53]:
np.log(a)

array([0.        , 0.69314718, 1.09861229])

In [54]:
e.dot(f)

array([[7., 7.],
       [7., 7.]])

In [55]:
a == b

array([[False,  True,  True],
       [False, False, False]])

In [56]:
a < 2

array([ True, False, False])

In [57]:
np.array_equal(a,b)

False

In [58]:
a.sum()

6

In [59]:
a.min()

1

In [60]:
b.max(axis=0)

array([4., 6., 5.])

In [61]:
b.cumsum(axis=1)

array([[ 1.5,  3.5,  6.5],
       [ 4. , 10. , 15. ]])

In [62]:
a.mean()

2.0

In [66]:
np.std(b)

1.5920810978785667

In [68]:
h = a.view()
h

array([1, 2, 3])

In [69]:
np.copy(a)

array([1, 2, 3])

In [70]:
h = a.copy()
h

array([1, 2, 3])

In [72]:
a.sort()
a

array([1, 2, 3])

In [74]:
c.sort(axis=0)
c

array([[[1.5, 2. , 1. ],
        [4. , 5. , 5. ]],

       [[3. , 2. , 3. ],
        [4. , 6. , 6. ]]])

In [75]:
a[2]

3

In [76]:
b[1,2]

5.0

In [77]:
b

array([[1.5, 2. , 3. ],
       [4. , 6. , 5. ]])

In [78]:
a[0:2]

array([1, 2])

In [80]:
b[0:2,1]

array([2., 6.])

In [81]:
b[:1]

array([[1.5, 2. , 3. ]])

In [82]:
c[1,...]

array([[3., 2., 3.],
       [4., 6., 6.]])

In [83]:
a[ : :-1]

array([3, 2, 1])

In [84]:
a[a<2]

array([1])

In [85]:
b[[1, 0, 1, 0], [0, 1, 2, 0]]

array([4. , 2. , 5. , 1.5])

In [86]:
b[[1,0,1,0]][:,[0,1,2,0]]

array([[4. , 6. , 5. , 4. ],
       [1.5, 2. , 3. , 1.5],
       [4. , 6. , 5. , 4. ],
       [1.5, 2. , 3. , 1.5]])

In [89]:
i = np.transpose(b)
i

array([[1.5, 4. ],
       [2. , 6. ],
       [3. , 5. ]])

In [90]:
i.T

array([[1.5, 2. , 3. ],
       [4. , 6. , 5. ]])

In [91]:
b.ravel()

array([1.5, 2. , 3. , 4. , 6. , 5. ])

In [92]:
g.reshape(3,-2)

array([[-0.5,  0. ],
       [ 0. , -3. ],
       [-4. , -2. ]])

In [94]:
np.append(h,g)

array([ 1. ,  2. ,  3. , -0.5,  0. ,  0. , -3. , -4. , -2. ])

In [95]:
np.insert(a,1,5)

array([1, 5, 2, 3])

In [96]:
np.delete(a,[1])

array([1, 3])

In [97]:
np.concatenate((a,d),axis=0)

array([ 1,  2,  3, 10, 15, 20])

In [99]:
np.vstack((a,b))

array([[1. , 2. , 3. ],
       [1.5, 2. , 3. ],
       [4. , 6. , 5. ]])

In [100]:
np.r_[e,f]

array([[7., 7.],
       [7., 7.],
       [1., 0.],
       [0., 1.]])

In [101]:
np.hstack((e,f))

array([[7., 7., 1., 0.],
       [7., 7., 0., 1.]])

In [102]:
np.column_stack((a,d))

array([[ 1, 10],
       [ 2, 15],
       [ 3, 20]])

In [104]:
np.c_[a,d]

array([[ 1, 10],
       [ 2, 15],
       [ 3, 20]])

In [105]:
np.hsplit(a,3)

[array([1]), array([2]), array([3])]

In [106]:
np.vsplit(c,2)

[array([[[1.5, 2. , 1. ],
         [4. , 5. , 5. ]]]),
 array([[[3., 2., 3.],
         [4., 6., 6.]]])]

SciPy
============

In [107]:
a = np.array([1, 2, 3])
b = np.array([(1.5, 2, 3), (4, 6, 5)], dtype = float)
c = np.array([[(1.5, 2, 3), (4, 6, 5)], [(3, 2, 1), (4, 5, 6)]], dtype = float)

In [108]:
np.mgrid[0:5,0:5]

array([[[0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3],
        [4, 4, 4, 4, 4]],

       [[0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4]]])

In [109]:
np.ogrid[0:2,0:2]

[array([[0],
        [1]]),
 array([[0, 1]])]

In [110]:
np.r_[3, [0]*5,-1:1:10j]

array([ 3.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        , -1.        , -0.77777778, -0.55555556, -0.33333333,
       -0.11111111,  0.11111111,  0.33333333,  0.55555556,  0.77777778,
        1.        ])

In [112]:
np.transpose(b)

array([[1.5, 4. ],
       [2. , 6. ],
       [3. , 5. ]])

In [114]:
b.flatten()

array([1.5, 2. , 3. , 4. , 6. , 5. ])

In [116]:
from numpy import poly1d

In [119]:
p = poly1d([3,4,5])
p

poly1d([3, 4, 5])

In [120]:
def myfunc(a):
    if a < 0:
        return a*2
    else:
        return a/2

In [122]:
np.vectorize(myfunc)

In [123]:
np.real(b)

array([[1.5, 2. , 3. ],
       [4. , 6. , 5. ]])

In [125]:
np.imag(b)

array([[0., 0., 0.],
       [0., 0., 0.]])

In [126]:
np.real_if_close(c,tol=1000)

array([[[1.5, 2. , 3. ],
        [4. , 6. , 5. ]],

       [[3. , 2. , 1. ],
        [4. , 5. , 6. ]]])

In [127]:
np.cast['f'](np.pi)

array(3.1415927, dtype=float32)

In [129]:
np.angle(b,deg=True)

array([[0., 0., 0.],
       [0., 0., 0.]])

In [132]:
g = np.linspace(0,np.pi,num=5)
g

array([0.        , 0.78539816, 1.57079633, 2.35619449, 3.14159265])

In [134]:
g[3:] += np.pi
np.unwrap(g)

array([0.        , 0.78539816, 1.57079633, 2.35619449, 3.14159265])

In [135]:
np.logspace(0,10,3)

array([1.e+00, 1.e+05, 1.e+10])

In [136]:
np.select([c<4],[c*2])

array([[[3., 4., 6.],
        [0., 0., 0.]],

       [[6., 4., 2.],
        [0., 0., 0.]]])

In [137]:
misc.facrotial(a)

NameError: name 'misc' is not defined

In [138]:
from scipy import linalg, sparse

In [141]:
A = np.matrix(np.random.random((2,2)))
B = np.asmatrix(b)
C = np.mat(np.random.random((10,5)))
D = np.mat([(3, 4), (5, 6)])

In [142]:
A.I

matrix([[ 1.66764083, -0.65292718],
        [-0.03604661,  1.05323937]])

In [143]:
linalg.inv(A)

array([[ 1.66764083, -0.65292718],
       [-0.03604661,  1.05323937]])

In [144]:
A.T

matrix([[0.60779384, 0.02080145],
        [0.37678531, 0.96234708]])

In [145]:
A.H

matrix([[0.60779384, 0.02080145],
        [0.37678531, 0.96234708]])

In [146]:
np.trace(A)

1.5701409207160728

In [147]:
linalg.norm(A)

1.1991351553504626

In [148]:
linalg.norm(A,1)

1.339132383871724

In [149]:
linalg.norm(A,np.inf)

0.984579149015622

In [150]:
np.linalg.matrix_rank(C)

5

In [151]:
linalg.det(A)

0.5770709482408256

In [153]:
linalg.solve(A,b)

array([[-0.11024746, -0.5822814 ,  1.73828661],
       [ 4.15888758,  6.24734302,  5.15805704]])

In [156]:
E = np.mat(a).T
E

matrix([[1],
        [2],
        [3]])

In [158]:
linalg.lstsq(E,E)

(array([[1.]]), array([2.11535103e-31]), 1, array([3.74165739]))

In [159]:
linalg.pinv(C)

array([[ 0.31867685,  0.70669747,  0.3469539 ,  0.1992002 , -0.33996966,
         0.02209875, -0.24587286, -0.59451919,  0.19128572, -0.017543  ],
       [-0.45099102, -0.65121396, -0.20763881,  0.48753988,  0.25831679,
         0.31403366,  0.6279174 ,  0.22896392,  0.02887972, -0.42200241],
       [ 0.25432902, -0.21440214, -0.55205009, -1.22225852, -0.31008789,
         0.22413866,  0.17004047,  0.14692778,  0.75019507,  0.6582085 ],
       [ 0.08136424, -0.40044067,  0.7118656 ,  0.63148651, -0.07943893,
        -0.40268534, -0.20825641,  0.5464141 , -0.2670518 , -0.11057848],
       [-0.06016413,  0.49310688, -0.17049413, -0.03950383,  0.54846314,
         0.13886682, -0.12598444,  0.03995854, -0.3535947 ,  0.17405756]])

In [160]:
linalg.pinv2(C)

array([[ 0.31867685,  0.70669747,  0.3469539 ,  0.1992002 , -0.33996966,
         0.02209875, -0.24587286, -0.59451919,  0.19128572, -0.017543  ],
       [-0.45099102, -0.65121396, -0.20763881,  0.48753988,  0.25831679,
         0.31403366,  0.6279174 ,  0.22896392,  0.02887972, -0.42200241],
       [ 0.25432902, -0.21440214, -0.55205009, -1.22225852, -0.31008789,
         0.22413866,  0.17004047,  0.14692778,  0.75019507,  0.6582085 ],
       [ 0.08136424, -0.40044067,  0.7118656 ,  0.63148651, -0.07943893,
        -0.40268534, -0.20825641,  0.5464141 , -0.2670518 , -0.11057848],
       [-0.06016413,  0.49310688, -0.17049413, -0.03950383,  0.54846314,
         0.13886682, -0.12598444,  0.03995854, -0.3535947 ,  0.17405756]])

In [162]:
F = np.eye(3, k=1)
F

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [164]:
G = np.mat(np.identity(2))
G

matrix([[1., 0.],
        [0., 1.]])

In [165]:
C [C > 0.5] = 0
C

matrix([[0.49996269, 0.11387248, 0.39555832, 0.46452632, 0.28995999],
        [0.        , 0.13321522, 0.14395322, 0.07825892, 0.        ],
        [0.        , 0.25820756, 0.31245051, 0.        , 0.28721676],
        [0.        , 0.        , 0.07019707, 0.48057647, 0.38234171],
        [0.02924688, 0.3212061 , 0.13857721, 0.20117991, 0.        ],
        [0.        , 0.        , 0.        , 0.3523363 , 0.        ],
        [0.43353908, 0.        , 0.3097956 , 0.09937872, 0.21725757],
        [0.12215707, 0.37729174, 0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.        , 0.43532455, 0.1972937 ],
        [0.4120541 , 0.21654137, 0.        , 0.        , 0.        ]])

In [166]:
H = sparse.csr_matrix(C)
H

<10x5 sparse matrix of type '<class 'numpy.float64'>'
	with 29 stored elements in Compressed Sparse Row format>

In [167]:
I = sparse.csc_matrix(D)
I

<10x5 sparse matrix of type '<class 'numpy.float64'>'
	with 29 stored elements in Compressed Sparse Column format>

In [168]:
J = sparse.dok_matrix(A)
J

<2x2 sparse matrix of type '<class 'numpy.float64'>'
	with 4 stored elements in Dictionary Of Keys format>

In [171]:
sparse.isspmatrix_csc(A)

False

In [174]:
A @ D

matrix([[3.70730806, 4.69188721],
        [4.87413974, 5.85728826]])

In [175]:
np.multiply(D,A)

matrix([[1.82338153, 1.50714122],
        [0.10400725, 5.77408247]])

In [176]:
np.dot(A,D)

matrix([[3.70730806, 4.69188721],
        [4.87413974, 5.85728826]])

In [177]:
np.vdot(A,D)

matrix([[1.82338153]])

In [178]:
np.inner(A,D)

matrix([[3.33052275, 5.29968105],
        [3.91179266, 5.87808971]])

In [179]:
np.outer(A,D)

array([[1.82338153, 2.43117537, 3.03896921, 3.64676306],
       [1.13035592, 1.50714122, 1.88392653, 2.26071184],
       [0.06240435, 0.0832058 , 0.10400725, 0.1248087 ],
       [2.88704123, 3.84938831, 4.81173539, 5.77408247]])

In [180]:
np.tensordot(A,D)

array(9.20861247)

In [181]:
np.kron(A,D)

matrix([[1.82338153, 2.43117537, 1.13035592, 1.50714122],
        [3.03896921, 3.64676306, 1.88392653, 2.26071184],
        [0.06240435, 0.0832058 , 2.88704123, 3.84938831],
        [0.10400725, 0.1248087 , 4.81173539, 5.77408247]])

In [182]:
linalg.expm(A)

array([[1.84450906, 0.83154181],
       [0.04590751, 2.62698607]])

In [185]:
linalg.logm(A)

array([[-0.50569211,  0.49053818],
       [ 0.02708148, -0.04409795]])

In [186]:
linalg.sinm(D)

array([[-0.07153039,  0.17875259],
       [ 0.22344073,  0.06253405]])

In [187]:
linalg.cosm(D)

array([[ 0.30988067, -0.82893511],
       [-1.03616888, -0.31182066]])

In [188]:
linalg.tanm(A)

array([[0.70915448, 0.79510408],
       [0.04389587, 1.45734375]])

In [189]:
linalg.sinhm(D)

array([[1716.2338286 , 2134.23383225],
       [2667.79229031, 3316.90920278]])

In [190]:
linalg.coshm(D)

array([[1717.05255912, 2133.70712649],
       [2667.13390811, 3317.33290398]])

In [191]:
linalg.tanhm(A)

array([[0.53962131, 0.21561238],
       [0.01190346, 0.74251156]])

In [193]:
linalg.sqrtm(A)

array([[0.7779826 , 0.21436494],
       [0.01183459, 0.97969901]])

In [194]:
linalg.funm(A, lambda x: x*x)

array([[0.37725104, 0.59160603],
       [0.03266121, 0.93394958]])

In [196]:
la, v = linalg.eig(A)
v

array([[-0.99846856, -0.70837986],
       [ 0.05532218, -0.7058314 ]])

In [197]:
l1, l2 = la

In [198]:
v[:,0]

array([-0.99846856,  0.05532218])

In [199]:
v[:,1]

array([-0.70837986, -0.7058314 ])

In [200]:
linalg.eigvals(A)

array([0.58691729+0.j, 0.98322363+0.j])

In [201]:
U,s,Vh = linalg.svd(B)

In [202]:
M,N = B.shape

In [204]:
Sig = linalg.diagsvd(s,M,N)
Sig

array([[9.55596322, 0.        , 0.        ],
       [0.        , 0.96621266, 0.        ]])

In [206]:
P,L,U = linalg.lu(C)
P

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [208]:
la, v = sparse.linalg.eigs(F,1)
v

array([[ 1.00000000e+00-1.62061339e-12j],
       [-9.67290065e-07-1.67541614e-06j],
       [-1.87144329e-12+3.24122678e-12j]])

In [209]:
sparse.linalg.svds(H,2)

(array([[-0.09196769, -0.65723002],
        [-0.05746334, -0.11036956],
        [-0.17733303, -0.25131215],
        [ 0.51184875, -0.38014245],
        [-0.08306599, -0.21388826],
        [ 0.31383602, -0.16616251],
        [-0.2889503 , -0.38504221],
        [-0.32409406, -0.11864221],
        [ 0.44266046, -0.27251886],
        [-0.45269553, -0.19555821]]),
 array([0.71598176, 1.26536072]),
 array([[-0.55840321, -0.43423303, -0.23066889,  0.63774544,  0.19924899],
        [-0.47168403, -0.24518336, -0.41884718, -0.59674668, -0.43111451]]))